version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the React app..."
      - npm run build
  post_build:
    commands:
      - echo "Uploading build folder to S3..."
      - aws s3 sync build/ s3://frontendcode01-deploy --delete
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - '**/*'
